import pandas as pd


first_llama_3_1_8b = pd.read_csv("./data/metrics/Llama3_1_8b_Model_metrics.csv")
second_llama_3_1_8b = pd.read_csv("./data/metrics/Llama3_1_8b_Model_2rd_metrics.csv")
thrid_llama_3_1_8b = pd.read_csv("./data/metrics/Llama3_1_8b_Model_3rd_metrics.csv")
print("llama_3_1_8b")
print("Precision")
print(first_llama_3_1_8b["precision"].mean())
print(second_llama_3_1_8b["precision"].mean())
print("Recall")
print(first_llama_3_1_8b["recall"].mean())
print("F1")
print(first_llama_3_1_8b["f1"].mean())
print("Cosine_sim")
print(first_llama_3_1_8b["cosine_sim"].mean())
print(thrid_llama_3_1_8b["cosine_sim"].mean())
print("Levenshtein")
print(first_llama_3_1_8b["levenshtein_distance"].mean())
print(thrid_llama_3_1_8b["levenshtein_distance"].mean())
print("")

first_llama_3_1_70b = pd.read_csv("./data/metrics/Llama3_1_70b_Model_metrics.csv")
second_llama_3_1_70b = pd.read_csv("./data/metrics/Llama3_1_70b_Model_2rd_metrics.csv")
thrid_llama_3_1_70b = pd.read_csv("./data/metrics/Llama3_1_70b_Model_3rd_metrics.csv")
print("llama_3_1_70b")
print("Precision")
print(first_llama_3_1_70b["precision"].mean())
print(second_llama_3_1_70b["precision"].mean())
print("Recall")
print(first_llama_3_1_70b["recall"].mean())
print("F1")
print(first_llama_3_1_70b["f1"].mean())
print("Cosine_sim")
print(first_llama_3_1_70b["cosine_sim"].mean())
print(thrid_llama_3_1_70b["cosine_sim"].mean())
print("Levenshtein")
print(first_llama_3_1_70b["levenshtein_distance"].mean())
print(thrid_llama_3_1_70b["levenshtein_distance"].mean())
print("")

first_llama_3_1_405b = pd.read_csv("./data/metrics/Llama3_1_405b_Model_metrics.csv")
second_llama_3_1_405b = pd.read_csv("./data/metrics/Llama3_1_405b_Model_2rd_metrics.csv")
thrid_llama_3_1_405b = pd.read_csv("./data/metrics/Llama3_1_405b_Model_3rd_metrics.csv")
print("llama_3_1_405b")
print("Precision")
print(first_llama_3_1_405b["precision"].mean())
print(second_llama_3_1_405b["precision"].mean())
print("Recall")
print(first_llama_3_1_405b["recall"].mean())
print("F1")
print(first_llama_3_1_405b["f1"].mean())
print("Cosine_sim")
print(first_llama_3_1_405b["cosine_sim"].mean())
print(thrid_llama_3_1_405b["cosine_sim"].mean())
print("Levenshtein")
print(first_llama_3_1_405b["levenshtein_distance"].mean())
print(thrid_llama_3_1_405b["levenshtein_distance"].mean())
print("")

first_haiku = pd.read_csv("./data/metrics/Haiku3Model_metrics.csv")
second_haiku = pd.read_csv("./data/metrics/Haiku3Model_2rd_metrics.csv")
thrid_haiku = pd.read_csv("./data/metrics/Haiku3Model_3rd_metrics.csv")
print("haiku")
print("Precision")
print(first_haiku["precision"].mean())
print(second_haiku["precision"].mean())
print("Recall")
print(first_haiku["recall"].mean())
print("F1")
print(first_haiku["f1"].mean())
print("Cosine_sim")
print(first_haiku["cosine_sim"].mean())
print(thrid_haiku["cosine_sim"].mean())
print("Levenshtein")
print(first_haiku["levenshtein_distance"].mean())
print(thrid_haiku["levenshtein_distance"].mean())
print("")

first_sonet_3_5 = pd.read_csv("./data/metrics/Sonet3_5Model_metrics.csv")
second_sonet_3_5 = pd.read_csv("./data/metrics/Sonet3_5Model_2rd_metrics.csv")
thrid_sonet_3_5 = pd.read_csv("./data/metrics/Sonet3_5Model_3rd_metrics.csv")
print("sonet_3_5")
print("Precision")
print(first_sonet_3_5["precision"].mean())
print(second_sonet_3_5["precision"].mean())
print("Recall")
print(first_sonet_3_5["recall"].mean())
print("F1")
print(first_sonet_3_5["f1"].mean())
print("Cosine_sim")
print(first_sonet_3_5["cosine_sim"].mean())
print(thrid_sonet_3_5["cosine_sim"].mean())
print("Levenshtein")
print(first_sonet_3_5["levenshtein_distance"].mean())
print(thrid_sonet_3_5["levenshtein_distance"].mean())
print("")

first_opus = pd.read_csv("./data/metrics/OpusModel_metrics.csv")
second_opus = pd.read_csv("./data/metrics/OpusModel_2rd_metrics.csv")
thrid_opus = pd.read_csv("./data/metrics/OpusModel_3rd_metrics.csv")
print("opus")
print("Precision")
print(first_opus["precision"].mean())
print(second_opus["precision"].mean())
print("Recall")
print(first_opus["recall"].mean())
print("F1")
print(first_opus["f1"].mean())
print("Cosine_sim")
print(first_opus["cosine_sim"].mean())
print(thrid_opus["cosine_sim"].mean())
print("Levenshtein")
print(first_opus["levenshtein_distance"].mean())
print(thrid_opus["levenshtein_distance"].mean())
print("")

first_BigMistral = pd.read_csv("./data/metrics/BigMistralModel_metrics.csv")
second_BigMistral = pd.read_csv("./data/metrics/BigMistralModel_2rd_metrics.csv")
thrid_BigMistral = pd.read_csv("./data/metrics/BigMistralModel_3rd_metrics.csv")
print("BigMistral")
print("Precision")
print(first_BigMistral["precision"].mean())
print(second_BigMistral["precision"].mean())
print("Recall")
print(first_BigMistral["recall"].mean())
print("F1")
print(first_BigMistral["f1"].mean())
print("Cosine_sim")
print(first_BigMistral["cosine_sim"].mean())
print(thrid_BigMistral["cosine_sim"].mean())
print("Levenshtein")
print(first_BigMistral["levenshtein_distance"].mean())
print(thrid_BigMistral["levenshtein_distance"].mean())
print("")