version: '3.8'

services:
  app:
    build: .
    container_name: carmina_app
    env_file:
      - .env
    volumes :
      - .:/app
    working_dir: /app
    command: python main.py
    # networks:
      # - anon_network


  # Servidor de métricas 
  # metrics:
    # image: grafana/grafana:latest
    # container_name: metrics_dashboard
    # environment:
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    # ports:
      # - "3000:3000"
    # networks:
      # - anon_network

# volumes:
  # pg_data:

# networks:
  # anon_network:
    # driver: bridge
