[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
markers =
    llm: tests related to LLM models
    label: tests related to label anonymization
    anthropic: tests related to Anthropic models
    openai: tests related to OpenAI models
    huggingface: tests related to Hugging Face models
    azure: tests related to Azure models
    haiku: tests related to Haiku models
    sonnet: tests related to Haiku models
    llama: tests related to Llama models
    deepseek: tests related to Deepseek models
log_cli = true
log_cli_level = INFO