from .masked_extractor import extract_labels as extract_labels_from_masked_text
from .identify_extractor import extract_labels as extract_labels_from_identify_text
from .identify_extractor import extract_clean_text_and_labels